# Site settings
title: IGO Infrastructure Géomatique Ouverte
# site.name
name: "IGO Infrastructure Géomatique Ouverte"

email: info@igouverte.org
description: IGO est une solution Web gratuite en géomatique.

# permalink: /:day-:month-:year-:title
  
# -------  URL  ------- # 
#Voir le document IGO_documentation.org
#ref: http://imakewebthings.com/blog/github-pages-email/

#baseurl pour site sur github: "/site-web"  pour un site avec un cname mettre juste ""
baseurl: ""
# url pour local : [http://localhost]
url: ""

encoding: utf-8

#redcarpet:  redcarpet appears to be The Standard GitHub Flavored Markdown, sinon c'est Kramdown
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty

# rouge: plus facile d'installation pour windows  sinon en general c'est pygments qui est utilisé
# note: As of August 1, commiting a _config.yml that uses rouge now causes "Page build failure" on GitHub with a misleading error message like "The file _posts/2014-08-01-blah.md contains syntax errors." Before you commit & push, you must set highlighter: pygments in _config.yml, even if you don't care to install pygments locally.
#ref: http://loyc.net/2014/blogging-on-github.html
highlighter: pygments
#rouge pas supporté par github mettre pygments

# ref: http://pixelcog.com/blog/2013/jekyll-from-scratch-core-architecture/

include: ['_pages']
relative_permalinks: false

pages:
- test1: communaute.md
- test2: contribuer.md




#Plugin redirect ref: https://github.com/jekyll/jekyll-redirect-from
#archives pour les archives du blogue : https://github.com/jekyll/jekyll-archives
gems:
  - jekyll-redirect-from


#plugin pour le sitemap
gems:
  - jekyll-sitemap
 
#pour un résumé de post du blogue à droite
#excerpt_separator: "<!-- excerpt -->"   

# navigation dans l'entete	
navigation:
    - text: FAQ 
      text2: FAQ
      url: /faq/  
      layout: general 
    - text: English
      url: /english/
      layout: general 
    - text2: Français
      url: /
      layout: general 

sass:
    sass_dir: _sass 
#Réseaux sociaux  voir référence: http://blog.florianbersier.com/implementation-social-sharing-jekyll/
